
#use_frameworks!
source 'https://cdn.cocoapods.org/'

target 'iosApp' do
  platform :ios, '14.1'
  pod 'SDWebImage', '~> 5.20.1'
  pod 'OpenKuiklyIOSRender', :path => '../'
  pod 'demo', :path => '../demo'
  pod 'WMPlayer', "~> 5.0" # 第三方播放器库
  pod 'libpag', "~> 4.3.21"
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'OpenKuiklyIOSRender'
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = "YES"
      end
    end
  end
end
